### ISSUE TITLE
RGB "gamma" values, worked with the inverse 

### ISSUE THREAD

**Issue by diegormsouza** [ssec/sift#243]
Hi all,

During the Joint Satellite Conference I saw a presentation from Jordan about SIFT and recommended it to my colleagues here at CPTEC. They really liked!

One of them tried to create the Fire Temperature RGB on SIFT (quick guide below):

http://rammb.cira.colostate.edu/training/visit/quick_guides/Fire_Temperature_RGB.pdf

However, using 0.4 as the "R" gamma from the recipe didn't give us the expected result. 

In the end (with some help from Scott Lindstrom) we could create this RGB on SIFT, however we had to use 1 / 0.4 as the gamma.

Please find the result below (recent fires in the Amazon Region).

So, as a suggestion from my colleagues, maybe the label could be changed to "1 / Gamma" or keep "Gamma" and change the code.

Obrigado!

![SIFT Fire Temperature Amazon](https://user-images.githubusercontent.com/54595784/66749146-6bd5fa80-ee5f-11e9-86a1-2a38e6635628.png)

**Comment by djhoese** [comment]
Thanks for making this issue.

From what I can tell and what I remember, I think this 1/gamma convention came from EUMETSAT. You can see examples and descriptions of this in this PDF: http://eumetrain.org/RGBguide/recipes/RGB_recipes.pdf

Since I was the one who coded this feature and work on the open source Pytroll/Satpy group, I borrowed their convention. Their convention was borrowed from EUMETSAT since most of the core Pytroll developers work in Europe.

I think it would be reasonable to change the text for "Gamma" to say "1 / Gamma". We'll discuss this at our next meeting. Thanks.

**Comment by ScottLindstrom** [comment]
I note that AWIPS definitions of the Dust RGB has gamma of 0.4 in the green value -- which is 1 over the value of the gamma in that EUMETRAIN pdf.

There is a lot of ambiguity in the meaning of gamma.

Scott
________________________________

**Comment by djhoese** [comment]
From Wikipedia (last paragraph under Terminology [here](https://en.wikipedia.org/wiki/Gamma_correction)):

> Without context, a value labeled gamma might be either the encoding or the decoding value. Caution must be taken to correctly interpret the value as that to be applied-to-compensate or to be compensated-by-applying its inverse. In common parlance, in many occasions the decoding value (as 2.2) is employed as if it were the encoding value, instead of its inverse (1/2.2 in this case), which is the real value that must be applied to encode gamma.

**Comment by djhoese** [comment]
@ScottLindstrom and I talked this through and turns out I was wrong about how SIFT does this and why.

Wikipedia defines "gamma correction" as `x^g` (`x` to the power of `g`) where `x` is your image value and `g` is your "gamma" value. Both SIFT and AWIPS treat the "Gamma" parameter in their tools as the `g` in this equation; that is `g` == "Gamma". NASA and EUMETSAT use gamma values in their guides as `1 / g` or the inverse of the exponent, but refer to it in their guides as "Gamma".

So, as wikipedia stated, without context we can't really assume what someone means by "gamma". I am not the project manager of SIFT so I can't say what will be done in the future, but since AWIPS defines "Gamma" as `g` then we will likely keep SIFT the way it is to match that. It is too bad that many RGB guides out there don't refer to the gamma value as "Gamma<sup>-1</sup>" or something like that. I'm guessing there is a long history to the naming/use of gamma that will be difficult to change.

**Comment by diegormsouza** [comment]
Uow, thanks for the quick feedback guys, really appreciatte it!

I don't see any problems keeping the Gamma as g, it is just a matter of making that clear during our training here when using the Quick Guides.  

Thanks!
