### ISSUE TITLE
GOES-18

### ISSUE THREAD

**Issue by GOESguy** [ssec/sift#325]
I have reason to think that SIFT doesn't handle GOES-18 files. I get a "unknow file" for a RadC file. I put a practice (DOE-2) file out on the ssec pub incoming ftp. (This is GOES-17 data, labeled as GOES-18.) Ideally SIFT would be updated to handle both GOES-18 and -19 files. Why wait? :)

**Comment by djhoese** [comment]
I downloaded `OR_ABI-L1b-RadC-M6C10_G18_s20212030201177_e20212030203561_c20212030203598.nc` and loaded it into SIFT using the current development version with the current development version of Satpy:

![sift_g18_screenshot](https://user-images.githubusercontent.com/1828519/128366353-a645e73a-f057-4374-b4e6-bd16bec9d67f.png)

Looks like the image and navigation is fine, but SIFT doesn't know what to call the satellite.

Looking into it further it looks like Satpy is not assigning the "platform_name" properly because it is missing definitions for G18/G19. I'll make an update to Satpy for that and a few updates to SIFT to try to be smarter about this. Thanks.
