### ISSUE TITLE
Allow setting of satpy config path via env variable

### ISSUE THREAD

**Issue by nedelceo** [ssec/sift#380]
At this moment setting extra [Satpy component configuration path](https://satpy.readthedocs.io/en/stable/config.html#component-configuration-path) is done by setting `satpy_extra_readers_import_path` in [external_satpy_and_readers.yaml](https://github.com/ssec/sift/blob/6ca36f789fce67d34affb05fa101ee026f623a00/uwsift/etc/SIFT/config/external_satpy_and_readers.yaml). After discussion on [gitter](https://matrix.to/#/!AXWZGEQAHtBDfySPVa:gitter.im/$zJJMG5dFJIh-WkI26SLAqUW7gWZ638jQwnjZ5AML7UE?via=gitter.im), I think this could be improved in two steps.

1) Rename `satpy_extra_readers_import_path` because now  the name is confusing. Since it it is not only related to readers definitions, but also to definitions of composites, enhancements, areas and so on. The variable could be renamed to e.g. `satpy_extra_config_path`.

2) Allow the use of environment variable to define satpy config path. Now environment variable `SATPY_CONFIG_PATH` is set to  `satpy_extra_readers_import_path`   https://github.com/ssec/sift/blob/6ca36f789fce67d34affb05fa101ee026f623a00/uwsift/__init__.py#L90-L93
 I think it would be useful not to reset  `SATPY_CONFIG_PATH` but append `satpy_extra_readers_import_path` to it  if this env variable is already defined.

**Comment by djhoese** [comment]
Sorry about not contributing to the discussion on gitter. I've been having a really hard time getting gitter to notify me at all.

I agree with all of this. I believe newer versions of `donfig` (the package I maintain and that we use for the configuration logic here) allow us to specify deprecated or renamed config entries. If anyone has time to put together a pull request these would be great changes.

One thing I'm thinking about the `satpy_extra_config_path`...I'm wondering if this is needed at all. I mean, the main reason for `satpy_extra_readers_import_path` is so that SIFT adds it as an importable location for Python. SIFT could just do this for all `SATPY_CONFIG_PATH` directories. It is a little risky security-wise. Otherwise though, this configuration value is a Satpy value, not a SIFT value. Would it be too complex to expect users to understand that they are configuring Satpy at this point and to specify a separate Satpy configuration file and/or environment variables specific to Satpy? I mean, these users would be customizing Satpy, so that seems like a reasonable assumption to me.

**Comment by djhoese** [comment]
Good point...well maybe I should make a donfig release then :wink:
