### ISSUE TITLE
Overview image of data layers are misaligned

### ISSUE THREAD

**Issue by ColinDuff** [ssec/sift#9]
![ndvi_screenshot_nans](https://user-images.githubusercontent.com/16986603/48076341-49fedd00-e1e5-11e8-985e-67db1b33157a.png)

In the satpy reader we have set some values to nan to remove them from the final image.

Here we can see some areas , that contain nans , display heavily pixelated data on the screen. In particular look at the 2 versions of Madagascar. 
Probing these pixels shows nan as the data values.
Only nans show this behaviour, 
Viewing the data with satpy also doesnt exhibit this behaviour. 
![ndvi_satpy_nans](https://user-images.githubusercontent.com/16986603/48075865-5e8ea580-e1e4-11e8-9a15-34fd32aa0311.png)

**Comment by djhoese** [comment]
I'm re-titling this issue to better describe what is going on. This is not image corruption. This is the "overview" image underneath the high resolution data being mis-aligned (bad navigation/pixel choices). This has never been a problem before because we've never had transparent layers like this.

In the simplest case, the overview image should be fixed to look "better". However, I have a feeling that even after that there is a chance that the large pixels of the overview image might still "stick out" of the edge of the valid data. Or similarly they will show underneath invalid pixels in other data cases (example, only a few pixels are invalid).

**Comment by djhoese** [comment]
@ColinDuff Also not all of your images seem to be showing up.

**Comment by ColinDuff** [comment]
hi, i inserted only 2 images - 1 sift image and 1 satpy image - how many do you see?

**Comment by djhoese** [comment]
I deleted my comment. A refresh of the page loaded the two images.

**Comment by ameraner** [comment]
Fixed in v2.0
